### ISSUE TITLE
Android Client does not connect to room when iceTransportsType is set to PeerConnection.IceTransportsType.RELAY

### ISSUE THREAD

**Issue by yellowDevUI** [livekit/client-sdk-android#512]
**Describe the bug**
Hello I have configured embedded turn server of livekit as bellow:
```
turn:
  enabled: true
  udp_port: 3478
  tls_port: 5349
  relay_range_start: 1024
  relay_range_end: 30000
  external_tls: true
  cert_file: /root/livekit/turn-certs/turn.crt
  key_file: /root/livekit/turn-certs/turn.key
  domain: turn.myhost.com
```
I want to use ONLY relay ice candidates. so iceTransportsPolicy must be "relay" instead of "all"
In React Client I did that like this:
```
    <LiveKitRoom
      video={true}
      audio={true}
      token={token}
      serverUrl={serverUrl}
      // Use the default LiveKit theme for nice styles.
      data-lk-theme="default"
      style={{ height: '100vh' }}
      connectOptions={{
        rtcConfig: {
          iceTransportPolicy: "relay"
        }
      }}
    >
```
and as I tested, react client successfully connects to room using relay, and in livekit server logs connectionType is "turn"
but in android client it does not work.
```
room.connect(
                url, token, ConnectOptions(
                    autoSubscribe = true, audio = true, video = true,
                    rtcConfig = PeerConnection.RTCConfiguration(emptyList()).apply {
                        iceTransportsType = PeerConnection.IceTransportsType.RELAY
                    }
                )
            )
```
if I set `iceTransportsType = PeerConnection.IceTransportsType.ALL` it connects without any problem but I want to use only relay and I want to enforce connection through embedded turrn.
what should I do? 
what's the problem?
